apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  googleCloudBuild:
    projectId: ticketing-dev-398401
  artifacts:
    - image: us.gcr.io/ticketing-dev-398401/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile